In [1]:
import pandas as pd
df_csv = pd.read_csv("test_Y3wMUE5_7gLdaTN.csv")
df_csv.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [3]:
df_excel = pd.read_excel("dataset (1).xlsx",sheet_name="Sheet1")
df_excel.head()

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Purchase_Date,Membership,Rating,Phone,Remarks
0,C001,Alice,25.0,Female,Chennai,2500.0,2024-01-10 00:00:00,Gold,4.5,9.876543e+09,Good
1,C002,Bob,32.0,Male,Bangalore,3200.0,2024-01-12 00:00:00,Silver,4.2,9.876543e+09,Good
2,C003,Charlie,NaN,male,Hyderabad,4100.0,2024-01-15 00:00:00,Gold,4.8,9.876543e+09,NaN
3,C004,David,28.0,M,Chennai,NaN,2024-01-18 00:00:00,Platinum,5.0,9.876543e+09,Excellent
4,C005,Eva,35.0,Female,Mumbai,5200.0,2024-01-20 00:00:00,Gold,NaN,9.876543e+09,Good

In [7]:
url = "https://en.wikipedia.org/wiki/Economy_of_India"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
tables = pd.read_html(url, storage_options=headers)
df_web = tables[0]
df_web.head()

,0,1
0,"Mumbai, the financial capital of India[1][2]","Mumbai, the financial capital of India[1][2]"
1,Currency,"Indian rupee (INR, ₹)"
2,Fiscal year,1 April – 31 March
3,Trade organisations,"WTO, WCO, SAFTA, BIMSTEC, BRICS, G-20, BIS, AI..."
4,Country group,Developing country[3] Lower-middle income econ...

In [8]:
df=pd.read_excel("dataset (1).xlsx")
df.to_excel("data.xlsx", index = False)
df.head()

,Customer_ID,Name,Age,Gender,City,Purchase_Amount,Purchase_Date,Membership,Rating,Phone,Remarks
0,C001,Alice,25.0,Female,Chennai,2500.0,2024-01-10 00:00:00,Gold,4.5,9.876543e+09,Good
1,C002,Bob,32.0,Male,Bangalore,3200.0,2024-01-12 00:00:00,Silver,4.2,9.876543e+09,Good
2,C003,Charlie,NaN,male,Hyderabad,4100.0,2024-01-15 00:00:00,Gold,4.8,9.876543e+09,NaN
3,C004,David,28.0,M,Chennai,NaN,2024-01-18 00:00:00,Platinum,5.0,9.876543e+09,Excellent
4,C005,Eva,35.0,Female,Mumbai,5200.0,2024-01-20 00:00:00,Gold,NaN,9.876543e+09,Good